name: Deploy

on: [push]

jobs:
  build:
    runs-on: rpi-arm64
    steps:
    - name: remove old directory
      run: sudo rm /app/adumanai -rf

    - name: Clone repository into /app
      run: |
        sudo git clone https://github.com/Ajithv14/adumanai.git /app/adumanai
        sudo cp /app/config.py /app/adumanai/config.py

    - name: Change ownership of /app
      run: |
          if [ ! -d "/var/run/uwsgi" ]; then
            sudo mkdir -p /var/run/uwsgi
            echo "/var/run/uwsgi directory created."
          else
            echo "/var/run/uwsgi directory already exists."
          fi
          sudo chown -R www-data:www-data /var/run/uwsgi
          sudo chown -R www-data:www-data /app/adumanai

    - name: restart app
      run: sudo systemctl restart app

    - name: Check app status
      run: |
        sudo systemctl status app | tee /tmp/app_status.log
        # Check for the presence of 'active (running)' in the log
        if grep -q 'active (running)' /tmp/app_status.log; then
          echo "App is running"
        else
          echo "App is not running"
          exit 1
        fi