name: Deploy

on: [push]

jobs:
  build:
    runs-on: rpi-arm64
    steps:
    - name: remove old directory
      run: sudo rm /app/adumanai -rf

    - name: Clone repository into /app
      run: |
        sudo git clone https://github.com/Ajithv14/adumanai.git /app/adumanai
        sudo cp /app/config.py /app/adumanai/config.py

    - name: Change ownership of /app
      run: sudo chown -R www-data:www-data /app/adumanai

    - name: restart app
      run: sudo systemctl restart app
